package android.ali.space.api.modelsRemote.LatestLaunch

data class LatestLaunchModel(
    val auto_update: Boolean,
    val capsules: List<Any>,
    val cores: List<Core>,
    val crew: List<Any>,
    val date_local: String,
    val date_precision: String,
    val date_unix: Int,
    val date_utc: String,
    val details: String,
    val failures: List<Any>,
    val fairings: Fairings,
    val flight_number: Int,
    val id: String,
    val launch_library_id: Any,
    val launchpad: String,
    val links: Links,
    val name: String,
    val net: Boolean,
    val payloads: List<String>,
    val rocket: String,
    val ships: List<String>,
    val static_fire_date_unix: Any,
    val static_fire_date_utc: Any,
    val success: Boolean,
    val tbd: Boolean,
    val upcoming: Boolean,
    val window: Int
)